In [166]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

# --- Load dataset ---
df = pd.read_csv("CrimeData.csv")

# --- Basic info ---
print("Shape:", df.shape)
display(df.head(15))
df.info()

# --- Missing values summary ---
print("\nMissing values (top 15):")
print(df.isna().sum().sort_values(ascending=False).head(15))

Shape: (1004991, 28)

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,211507896,04/11/2021 12:00:00 AM,11/07/2020 12:00:00 AM,845,15,N Hollywood,1502,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,7800 BEEMAN AV,NaN,34.2124,-118.4092
1,201516622,10/21/2020 12:00:00 AM,10/18/2020 12:00:00 AM,1845,15,N Hollywood,1521,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",...,IC,Invest Cont,230.0,NaN,NaN,NaN,ATOLL AV,N GAULT,34.1993,-118.4203
2,240913563,12/10/2024 12:00:00 AM,10/30/2020 12:00:00 AM,1240,9,Van Nuys,933,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,14600 SYLVAN ST,NaN,34.1847,-118.4509
3,210704711,12/24/2020 12:00:00 AM,12/24/2020 12:00:00 AM,1310,7,Wilshire,782,1,331,THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...,...,IC,Invest Cont,331.0,NaN,NaN,NaN,6000 COMEY AV,NaN,34.0339,-118.3747
4,201418201,10/03/2020 12:00:00 AM,09/29/2020 12:00:00 AM,1830,14,Pacific,1454,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),...,IC,Invest Cont,420.0,NaN,NaN,NaN,4700 LA VILLA MARINA,NaN,33.9813,-118.4350
5,240412063,12/11/2024 12:00:00 AM,11/11/2020 12:00:00 AM,1210,4,Hollenbeck,429,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,5300 CRONUS ST,NaN,34.0830,-118.1678
6,240317069,12/16/2024 12:00:00 AM,04/16/2020 12:00:00 AM,1350,3,Southwest,396,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,900 W 40TH PL,NaN,34.0100,-118.2900
7,201115217,10/29/2020 12:00:00 AM,07/07/2020 12:00:00 AM,1400,11,Northeast,1133,2,812,CRM AGNST CHLD (13 OR UNDER) (14-15 & SUSP 10 ...,...,AO,Adult Other,812.0,860.0,NaN,NaN,3000 ACRESITE ST,NaN,34.1107,-118.2589
8,241708596,04/20/2024 12:00:00 AM,03/02/2020 12:00:00 AM,1200,17,Devonshire,1729,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,17700 SIMONDS ST,NaN,34.2763,-118.5210
9,242113813,12/18/2024 12:00:00 AM,09/01/2020 12:00:00 AM,900,21,Topanga,2196,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,20900 MARMORA ST,NaN,34.1493,-118.5886
10,240605846,02/06/2024 12:00:00 AM,06/20/2020 12:00:00 AM,1,6,Hollywood,657,2,812,CRM AGNST CHLD (13 OR UNDER) (14-15 & SUSP 10 ...,...,AA,Adult Arrest,812.0,860.0,NaN,NaN,1000 N RIDGEWOOD PL,NaN,34.0878,-118.3146
11,242014110,12/18/2024 12:00:00 AM,11/17/2020 12:00:00 AM,1320,20,Olympic,2023,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,400 S ARDMORE AV,NaN,34.0672,-118.3016
12,202113531,09/06/2020 12:00:00 AM,09/05/2020 12:00:00 AM,1500,21,Topanga,2149,1,510,VEHICLE - STOLEN,...,AA,Adult Arrest,510.0,NaN,NaN,NaN,19700 VANOWEN ST,NaN,34.1938,-118.5631
13,201710725,07/03/2020 12:00:00 AM,07/02/2020 12:00:00 AM,500,17,Devonshire,1762,1,310,BURGLARY,...,IC,Invest Cont,310.0,NaN,NaN,NaN,9500 COZYCROFT AV,NaN,34.2427,-118.5820
14,201406733,02/16/2020 12:00:00 AM,02/13/2020 12:00:00 AM,2300,14,Pacific,1406,1,330,BURGLARY FROM VEHICLE,...,IC,Invest Cont,330.0,NaN,NaN,NaN,3300 MOTOR AV,NaN,34.0240,-118.4090

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1004991 entries, 0 to 1004990
Data columns (total 28 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   DR_NO           1004991 non-null  int64
 1   Date Rptd       1004991 non-null  object
 2   DATE OCC        1004991 non-null  object
 3   TIME OCC        1004991 non-null  int64
 4   AREA            1004991 non-null  int64
 5   AREA NAME       1004991 non-null  object
 6   Rpt Dist No     1004991 non-null  int64
 7   Part 1-2        1004991 non-null  int64
 8   Crm Cd          1004991 non-null  int64
 9   Crm Cd Desc     1004991 non-null  object
 10  Mocodes         853372 non-null   object
 11  Vict Age        1004991 non-null  int64
 12  Vict Sex        860347 non-null   object
 13  Vict Descent    860335 non-null   object
 14  Premis Cd       1004975 non-null  float64
 15  Premis Desc     1004403 non-null  object
 16  Weapon Used Cd  327247 non-null   float64
 17  Weapon Desc     327247 non-null   object
 18  Status          1004990 non-null  object
 19  Status Desc     1004991 non-null  object
 20  Crm Cd 1        1004980 non-null  float64
 21  Crm Cd 2        69160 non-null    float64
 22  Crm Cd 3        2314 non-null     float64
 23  Crm Cd 4        64 non-null       float64
 24  LOCATION        1004991 non-null  object
 25  Cross Street    154236 non-null   object
 26  LAT             1004991 non-null  float64
 27  LON             1004991 non-null  float64
dtypes: float64(8), int64(7), object(13)
memory usage: 214.7+ MB

Missing values (top 15):
Crm Cd 4          1004927
Crm Cd 3          1002677
Crm Cd 2           935831
Cross Street       850755
Weapon Used Cd     677744
Weapon Desc        677744
Mocodes            151619
Vict Descent       144656
Vict Sex           144644
Premis Desc           588
Premis Cd              16
Crm Cd 1               11
Status                  1
LAT                     0
LOCATION                0
dtype: int64

In [167]:
# --- Clean and Standardize Columns ---
df_clean = df.copy()

# Remove redundant columns
df_clean.drop(columns=["Crm Cd 1"], inplace=True, errors="ignore")

# Convert date columns to datetime (explicit format)
DATE_FORMAT = "%m/%d/%Y %I:%M:%S %p"

for col in ["DATE OCC", "Date Rptd"]:
    df_clean[col] = pd.to_datetime(df_clean[col], format=DATE_FORMAT, errors="coerce")

# Ensure LAT/LON are numeric
for col in ["LAT", "LON"]:
    df_clean[col] = pd.to_numeric(df_clean[col], errors="coerce")

# Check results
df_clean.info()
df_clean[["DATE OCC", "Date Rptd", "TIME OCC", "LAT", "LON"]].head(15)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1004991 entries, 0 to 1004990
Data columns (total 27 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   DR_NO           1004991 non-null  int64
 1   Date Rptd       1004991 non-null  datetime64[ns]
 2   DATE OCC        1004991 non-null  datetime64[ns]
 3   TIME OCC        1004991 non-null  int64
 4   AREA            1004991 non-null  int64
 5   AREA NAME       1004991 non-null  object
 6   Rpt Dist No     1004991 non-null  int64
 7   Part 1-2        1004991 non-null  int64
 8   Crm Cd          1004991 non-null  int64
 9   Crm Cd Desc     1004991 non-null  object
 10  Mocodes         853372 non-null   object
 11  Vict Age        1004991 non-null  int64
 12  Vict Sex        860347 non-null   object
 13  Vict Descent    860335 non-null   object
 14  Premis Cd       1004975 non-null  float64
 15  Premis Desc     1004403 non-null  object
 16  Weapon Used Cd  327247 non-null   float64
 17  Weapon Desc     327247 non-null   object
 18  Status          1004990 non-null  object
 19  Status Desc     1004991 non-null  object
 20  Crm Cd 2        69160 non-null    float64
 21  Crm Cd 3        2314 non-null     float64
 22  Crm Cd 4        64 non-null       float64
 23  LOCATION        1004991 non-null  object
 24  Cross Street    154236 non-null   object
 25  LAT             1004991 non-null  float64
 26  LON             1004991 non-null  float64
dtypes: datetime64[ns](2), float64(7), int64(7), object(11)
memory usage: 207.0+ MB

     DATE OCC  Date Rptd  TIME OCC      LAT       LON
0  2020-11-07 2021-04-11       845  34.2124 -118.4092
1  2020-10-18 2020-10-21      1845  34.1993 -118.4203
2  2020-10-30 2024-12-10      1240  34.1847 -118.4509
3  2020-12-24 2020-12-24      1310  34.0339 -118.3747
4  2020-09-29 2020-10-03      1830  33.9813 -118.4350
5  2020-11-11 2024-12-11      1210  34.0830 -118.1678
6  2020-04-16 2024-12-16      1350  34.0100 -118.2900
7  2020-07-07 2020-10-29      1400  34.1107 -118.2589
8  2020-03-02 2024-04-20      1200  34.2763 -118.5210
9  2020-09-01 2024-12-18       900  34.1493 -118.5886
10 2020-06-20 2024-02-06         1  34.0878 -118.3146
11 2020-11-17 2024-12-18      1320  34.0672 -118.3016
12 2020-09-05 2020-09-06      1500  34.1938 -118.5631
13 2020-07-02 2020-07-03       500  34.2427 -118.5820
14 2020-02-13 2020-02-16      2300  34.0240 -118.4090

In [168]:
# Pad TIME OCC values to 4 digits (e.g. 1 -> 0001)
df_clean["TIME OCC"] = df_clean["TIME OCC"].astype(str).str.zfill(4)

# Convert to readable "HH:MM" format
df_clean["TIME OCC"] = df_clean["TIME OCC"].str.replace(
    r"(\d{2})(\d{2})", r"\1:\2", regex=True
)

# Quick sanity check
df_clean[["DATE OCC", "TIME OCC"]].head(15)

     DATE OCC TIME OCC
0  2020-11-07    08:45
1  2020-10-18    18:45
2  2020-10-30    12:40
3  2020-12-24    13:10
4  2020-09-29    18:30
5  2020-11-11    12:10
6  2020-04-16    13:50
7  2020-07-07    14:00
8  2020-03-02    12:00
9  2020-09-01    09:00
10 2020-06-20    00:01
11 2020-11-17    13:20
12 2020-09-05    15:00
13 2020-07-02    05:00
14 2020-02-13    23:00

In [169]:
# --- Handle Missing Values and Duplicates ---

# Remove duplicate rows (if any)
dup_count = df_clean.duplicated().sum()
print("Duplicate rows:", dup_count)
if dup_count > 0:
    df_clean = df_clean.drop_duplicates()

# Fill categorical missing values with 'Unknown'
for col in ["AREA NAME", "Crm Cd Desc", "Status Desc", "LOCATION", "Cross Street"]:
    if col in df_clean.columns:
        df_clean[col] = df_clean[col].fillna("Unknown")

# Check columns with high missing ratio (>50%)
missing_ratio = df_clean.isna().sum() / len(df_clean) * 100
high_missing = missing_ratio[missing_ratio > 50].sort_values(ascending=False)
print("\nColumns with >50% missing values:")
print(high_missing)

# Quick check again
df_clean.info()

Duplicate rows: 0

Columns with >50% missing values:
Crm Cd 4          99.993632
Crm Cd 3          99.769749
Crm Cd 2          93.118346
Weapon Used Cd    67.437818
Weapon Desc       67.437818
dtype: float64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1004991 entries, 0 to 1004990
Data columns (total 27 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   DR_NO           1004991 non-null  int64
 1   Date Rptd       1004991 non-null  datetime64[ns]
 2   DATE OCC        1004991 non-null  datetime64[ns]
 3   TIME OCC        1004991 non-null  object
 4   AREA            1004991 non-null  int64
 5   AREA NAME       1004991 non-null  object
 6   Rpt Dist No     1004991 non-null  int64
 7   Part 1-2        1004991 non-null  int64
 8   Crm Cd          1004991 non-null  int64
 9   Crm Cd Desc     1004991 non-null  object
 10  Mocodes         853372 non-null   object
 11  Vict Age        1004991 non-null  int64
 12  Vict Sex        860347 non-null   object
 13  Vict Descent    860335 non-null   object
 14  Premis Cd       1004975 non-null  float64
 15  Premis Desc     1004403 non-null  object
 16  Weapon Used Cd  327247 non-null   float64
 17  Weapon Desc     327247 non-null   object
 18  Status          1004990 non-null  object
 19  Status Desc     1004991 non-null  object
 20  Crm Cd 2        69160 non-null    float64
 21  Crm Cd 3        2314 non-null     float64
 22  Crm Cd 4        64 non-null       float64
 23  LOCATION        1004991 non-null  object
 24  Cross Street    1004991 non-null  object
 25  LAT             1004991 non-null  float64
 26  LON             1004991 non-null  float64
dtypes: datetime64[ns](2), float64(7), int64(6), object(12)
memory usage: 207.0+ MB

In [170]:
# --- Combine Crm Cd 2–4 into a single column ---
crm_cols = ["Crm Cd 2", "Crm Cd 3", "Crm Cd 4"]

# Create 'Additional Crm Cd' by combining non-null values
df_clean["Additional Crm Cd"] = df_clean[crm_cols].apply(
    lambda row: ", ".join([str(int(x)) for x in row if not pd.isna(x)]),
    axis=1
)

# Drop original Crm Cd 2–4 columns
df_clean.drop(columns=crm_cols, inplace=True)

# Check result
df_clean[["Crm Cd", "Additional Crm Cd", "Crm Cd Desc"]].head(10)

   Crm Cd Additional Crm Cd                                        Crm Cd Desc
0     354                                                    THEFT OF IDENTITY
1     230                       ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT
2     354                                                    THEFT OF IDENTITY
3     331                    THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...
4     420                      THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER)
5     354                                                    THEFT OF IDENTITY
6     354                                                    THEFT OF IDENTITY
7     812               860  CRM AGNST CHLD (13 OR UNDER) (14-15 & SUSP 10 ...
8     354                                                    THEFT OF IDENTITY
9     354                                                    THEFT OF IDENTITY

In [171]:
# --- Consolidate crime codes with primary precedence (robust to missing 'Additional Crm Cd') ---

import numpy as np
import pandas as pd
import re

# 0) If 'Additional Crm Cd' is missing but 2–4가 남아있다면 즉석 생성
crm_cols = ["Crm Cd 2", "Crm Cd 3", "Crm Cd 4"]
if "Additional Crm Cd" not in df_clean.columns and any(c in df_clean.columns for c in crm_cols):
    df_clean["Additional Crm Cd"] = df_clean[crm_cols].apply(
        lambda row: ", ".join([str(int(x)) for x in row if pd.notna(x)]),
        axis=1
    )

# 1) Build code -> description dictionary (from primary rows)
code2desc = (
    df_clean[["Crm Cd", "Crm Cd Desc"]]
    .dropna()
    .drop_duplicates(subset=["Crm Cd"])
    .set_index("Crm Cd")["Crm Cd Desc"]
    .to_dict()
)

# 2) Parser for "860, 420" -> [860, 420]
def parse_additional(s):
    if pd.isna(s) or str(s).strip() == "":
        return []
    return [int(t) for t in re.findall(r"\d{1,4}", str(s))]

# 3) Build add_lists from 'Additional Crm Cd' if present; otherwise empty
add_lists = (
    df_clean["Additional Crm Cd"].apply(parse_additional)
    if "Additional Crm Cd" in df_clean.columns
    else pd.Series([[]] * len(df_clean), index=df_clean.index)
)

# 4) Primary first, then additional (dedup, keep order)
def unify_codes(primary_code, extras):
    out = []
    if pd.notna(primary_code):
        out.append(int(primary_code))
    for c in extras or []:
        if c not in out:
            out.append(c)
    return out

df_clean["All_Crm_Cd_list"] = [unify_codes(pc, ex) for pc, ex in zip(df_clean["Crm Cd"], add_lists)]

# 5) Descriptions for unified list
def codes_to_desc(code_list):
    if not code_list:
        return ""
    seen, descs = set(), []
    for c in code_list:
        d = code2desc.get(c, f"Code {c}")
        if d not in seen:
            seen.add(d)
            descs.append(d)
    return ", ".join(descs)

df_clean["All_Crm_Cd_Desc"] = df_clean["All_Crm_Cd_list"].apply(codes_to_desc)

# 6) Flags + final string column
df_clean["Has_Multiple_Crimes"] = df_clean["All_Crm_Cd_list"].apply(lambda xs: len(xs) > 1)
df_clean["All_Crm_Cd"] = df_clean["All_Crm_Cd_list"].apply(lambda xs: ", ".join(str(x) for x in xs))

# 7) Preview BEFORE dropping helpers (to verify multiples show up)
print(df_clean[["Crm Cd", "Additional Crm Cd"]].head(10) if "Additional Crm Cd" in df_clean.columns else "No 'Additional Crm Cd' present")
print(df_clean[["Crm Cd", "All_Crm_Cd", "All_Crm_Cd_Desc"]].head(10))
print("Share of multi-offense rows:", float(df_clean["Has_Multiple_Crimes"].mean()))

# 8) Drop helpers
df_clean.drop(columns=["All_Crm_Cd_list", "Additional Crm Cd", *[c for c in crm_cols if c in df_clean.columns]], inplace=True, errors="ignore")
df_clean[["Crm Cd", "All_Crm_Cd", "All_Crm_Cd_Desc"]].head(10)

   Crm Cd Additional Crm Cd
0     354
1     230
2     354
3     331
4     420
5     354
6     354
7     812               860
8     354
9     354
   Crm Cd All_Crm_Cd                                    All_Crm_Cd_Desc
0     354        354                                  THEFT OF IDENTITY
1     230        230     ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT
2     354        354                                  THEFT OF IDENTITY
3     331        331  THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...
4     420        420    THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER)
5     354        354                                  THEFT OF IDENTITY
6     354        354                                  THEFT OF IDENTITY
7     812   812, 860  CRM AGNST CHLD (13 OR UNDER) (14-15 & SUSP 10 ...
8     354        354                                  THEFT OF IDENTITY
9     354        354                                  THEFT OF IDENTITY
Share of multi-offense rows: 0.06720358689779311

   Crm Cd All_Crm_Cd                                    All_Crm_Cd_Desc
0     354        354                                  THEFT OF IDENTITY
1     230        230     ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT
2     354        354                                  THEFT OF IDENTITY
3     331        331  THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...
4     420        420    THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER)
5     354        354                                  THEFT OF IDENTITY
6     354        354                                  THEFT OF IDENTITY
7     812   812, 860  CRM AGNST CHLD (13 OR UNDER) (14-15 & SUSP 10 ...
8     354        354                                  THEFT OF IDENTITY
9     354        354                                  THEFT OF IDENTITY

In [172]:
# --- Feature Engineering: Time and Date ---

# Derive year, month, day of week, weekend flag
df_clean["YEAR"] = df_clean["DATE OCC"].dt.year
df_clean["MONTH"] = df_clean["DATE OCC"].dt.month
df_clean["DAY_OF_WEEK"] = df_clean["DATE OCC"].dt.day_name()
df_clean["IS_WEEKEND"] = df_clean["DAY_OF_WEEK"].isin(["Saturday", "Sunday"])

# Derive time period from TIME OCC (without changing it)
def to_time_period(v):
    try:
        hour = int(float(v)) // 100
    except:
        return "Unknown"
    if 5 <= hour < 12: return "Morning"
    if 12 <= hour < 18: return "Afternoon"
    if 18 <= hour < 24: return "Evening"
    if 0 <= hour < 5: return "Night"
    return "Unknown"

df_clean["TIME_PERIOD"] = df_clean["TIME OCC"].apply(to_time_period)

# Check result
df_clean[["DATE OCC", "TIME OCC", "TIME_PERIOD", "DAY_OF_WEEK", "IS_WEEKEND"]].head(10)

    DATE OCC TIME OCC TIME_PERIOD DAY_OF_WEEK  IS_WEEKEND
0 2020-11-07    08:45     Unknown    Saturday        True
1 2020-10-18    18:45     Unknown      Sunday        True
2 2020-10-30    12:40     Unknown      Friday       False
3 2020-12-24    13:10     Unknown    Thursday       False
4 2020-09-29    18:30     Unknown     Tuesday       False
5 2020-11-11    12:10     Unknown   Wednesday       False
6 2020-04-16    13:50     Unknown    Thursday       False
7 2020-07-07    14:00     Unknown     Tuesday       False
8 2020-03-02    12:00     Unknown      Monday       False
9 2020-09-01    09:00     Unknown     Tuesday       False

In [173]:
import pandas as pd, re

MAP_PATH = "MoCodes.csv"  # your uploaded file

# Load and normalize columns
mo_map_df = pd.read_csv(MAP_PATH, dtype=str, encoding_errors="ignore")
mo_map_df.columns = (
    mo_map_df.columns
    .str.replace("\ufeff", "", regex=False)  # strip BOM
    .str.strip()
    .str.lower()
)

print("Columns in MoCodes.csv:", list(mo_map_df.columns))
display(mo_map_df.head(10))
print("Rows in mapping csv:", len(mo_map_df))

# Try to find code/description columns by common names
code_col_candidates = [c for c in mo_map_df.columns if c in ["code","codes","mocode","mo code","mo_code","mo codes","mo_codes"]]
desc_col_candidates = [c for c in mo_map_df.columns if c in ["description","desc","details","text"]]

print("Detected code cols:", code_col_candidates)
print("Detected desc cols:", desc_col_candidates)

# Pick the first plausible columns (adjust if needed)
CODE_COL = code_col_candidates[0] if code_col_candidates else "code"
DESC_COL = desc_col_candidates[0] if desc_col_candidates else "description"

# If columns are named differently, try to rename smartly
if CODE_COL not in mo_map_df.columns or DESC_COL not in mo_map_df.columns:
    # Heuristic: if exactly two columns, assume first is code, second is description
    if len(mo_map_df.columns) == 2:
        mo_map_df = mo_map_df.rename(columns={mo_map_df.columns[0]:"code", mo_map_df.columns[1]:"description"})
        CODE_COL, DESC_COL = "code", "description"
    else:
        print("⚠️ Couldn't auto-detect columns. Please confirm column names.")

# Clean and normalize code keys to 4-digit strings
def normalize_code(s):
    if s is None: return None
    s = str(s)
    # keep digits only (handles '0377,' '0377.' etc.)
    m = re.search(r"(\d{1,4})", s)
    if not m: return None
    return m.group(1).zfill(4)

mo_map_df = mo_map_df.dropna(subset=[CODE_COL, DESC_COL])
mo_map_df["__code"] = mo_map_df[CODE_COL].apply(normalize_code)
mo_map_df["__desc"] = mo_map_df[DESC_COL].astype(str).str.strip()

# Drop rows that failed to normalize
mo_map_df = mo_map_df.dropna(subset=["__code","__desc"]).drop_duplicates("__code", keep="first")

# Build dict
mo_map_str = dict(zip(mo_map_df["__code"], mo_map_df["__desc"]))

print("Mapping size:", len(mo_map_str))
print("Has 0377?", "0377" in mo_map_str)
if "0377" in mo_map_str:
    print("0377 ->", mo_map_str["0377"])

# Peek a few keys
print("Some keys:", list(mo_map_str.keys())[:15])

Columns in MoCodes.csv: ['codes', 'description']

  codes          description
0  0100  Suspect Impersonate
1  0101           Aid victim
2  0102                Blind
3  0103             Crippled
4  0104             Customer
5  0105             Delivery
6  0106               Doctor
7  0107                  God
8  0108               Infirm
9  0109            Inspector

Rows in mapping csv: 778
Detected code cols: ['codes']
Detected desc cols: ['description']
Mapping size: 777
Has 0377? True
0377 -> Takes vict's identification/driver license
Some keys: ['0100', '0101', '0102', '0103', '0104', '0105', '0106', '0107', '0108', '0109', '0110', '0112', '0113', '0114', '0115']

In [174]:
# Strict decoder: extract only digits, pad to 4, then lookup
def decode_mocodes_with_csv(val, mapping):
    if pd.isna(val):
        return []
    # replace any non-digit with space, then split
    tokens = re.sub(r"\D+", " ", str(val)).strip().split()
    out = []
    for t in tokens:
        key = t.zfill(4)
        out.append(mapping.get(key, f"Unknown({key})"))
    return out

df_clean["MoCodes_desc"] = df_clean["Mocodes"].apply(
    lambda v: ", ".join(decode_mocodes_with_csv(v, mo_map_str))
)

df_clean[["Mocodes", "MoCodes_desc"]].head(10)

,Mocodes,MoCodes_desc
0,0377,Takes vict's identification/driver license
1,0416 0334 2004 1822 1414 0305 0319 0400,"Hit-Hit w/ weapon, Brandishes weapon, Suspect ..."
2,0377,Takes vict's identification/driver license
3,0344,Removes vict property
4,1300 0344 1606 2032,"Vehicle involved, Removes vict property, Open/..."
5,0100,Suspect Impersonate
6,0100 0928 1822,"Suspect Impersonate, Forged or Fraudulent cred..."
7,1259 0448 0304 1822 0500 0522,"Victim is 14 years old thru 17 years old, Grab..."
8,1501,Other MO (see rpt)
9,0930,Unauthorized use of victim's credit/debit card...

In [175]:
# Drop the decoded list column
df_clean = df_clean.drop(columns=["MoCodes_decoded"], errors="ignore")

# Check results
df_clean[["Mocodes", "MoCodes_desc"]].head()

,Mocodes,MoCodes_desc
0,0377,Takes vict's identification/driver license
1,0416 0334 2004 1822 1414 0305 0319 0400,"Hit-Hit w/ weapon, Brandishes weapon, Suspect ..."
2,0377,Takes vict's identification/driver license
3,0344,Removes vict property
4,1300 0344 1606 2032,"Vehicle involved, Removes vict property, Open/..."

In [176]:
print("Vict Sex unique values:", sorted(df_clean["Vict Sex"].dropna().unique()))
print("Vict Descent unique values:", sorted(df_clean["Vict Descent"].dropna().unique()))
print("\nMissing counts:")
print(df_clean[["Vict Sex","Vict Descent"]].isna().sum())

Vict Sex unique values: ['-', 'F', 'H', 'M', 'X']
Vict Descent unique values: ['-', 'A', 'B', 'C', 'D', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'O', 'P', 'S', 'U', 'V', 'W', 'X', 'Z']

Missing counts:
Vict Sex        144644
Vict Descent    144656
dtype: int64

In [177]:
# --- Normalize Vict Sex ---
valid_sex = {"M", "F"}

# keep NaN as NaN (use pandas' string dtype), normalize case/whitespace
df_clean["Vict Sex"] = (
    df_clean["Vict Sex"]
    .astype("string")
    .str.strip()
    .str.upper()
)

# map explicit invalid codes to UNKNOWN
df_clean["Vict Sex"] = df_clean["Vict Sex"].replace({"X": "UNKNOWN", "-": "UNKNOWN"})

# allow only M/F/UNKNOWN; everything else -> UNKNOWN, then fill NaN as UNKNOWN
df_clean["Vict Sex"] = (
    df_clean["Vict Sex"]
    .where(df_clean["Vict Sex"].isin(valid_sex | {"UNKNOWN"}), "UNKNOWN")
    .fillna("UNKNOWN")
)

# final presentation casing
df_clean["Vict Sex"] = df_clean["Vict Sex"].replace({"UNKNOWN": "Unknown"})

# --- Normalize Vict Descent ---
# LAPD descent codes observed (exclude '-', 'X')
valid_descent = {"A","B","C","D","F","G","H","I","J","K","L","O","P","S","U","V","W","Z"}

df_clean["Vict Descent"] = (
    df_clean["Vict Descent"]
    .astype("string")
    .str.strip()
    .str.upper()
)

df_clean["Vict Descent"] = df_clean["Vict Descent"].replace({"X": "UNKNOWN", "-": "UNKNOWN"})

df_clean["Vict Descent"] = (
    df_clean["Vict Descent"]
    .where(df_clean["Vict Descent"].isin(valid_descent | {"UNKNOWN"}), "UNKNOWN")
    .fillna("UNKNOWN")
)
df_clean["Vict Descent"] = df_clean["Vict Descent"].replace({"UNKNOWN": "Unknown"})

# --- Quick checks ---
print("Vict Sex ->", df_clean["Vict Sex"].value_counts(dropna=False))
print("Vict Descent ->", df_clean["Vict Descent"].value_counts(dropna=False).head(15))

df_clean[["Vict Age", "Vict Sex", "Vict Descent"]].head(15)

Vict Sex -> Vict Sex
M          403879
F          358580
Unknown    242532
Name: count, dtype: Int64
Vict Descent -> Vict Descent
H          296404
Unknown    251343
W          201442
B          135816
O           78005
A           21340
K            5990
F            4838
C            4631
J            1586
V            1195
I            1015
Z             577
P             288
U             221
Name: count, dtype: Int64

    Vict Age Vict Sex Vict Descent
0         31        M            H
1         32        M            H
2         30        M            W
3         47        F            A
4         63        M            H
5         35        M            B
6         21        F            B
7         14        F            H
8         43        M            W
9         57        M            W
10        13        M            H
11        34        F            A
12         0  Unknown      Unknown
13         0  Unknown      Unknown
14        32        M            W

In [178]:
# Mapping from LAPD official metadata
descent_map = {
    "A": "Other Asian",
    "B": "Black",
    "C": "Chinese",
    "D": "Cambodian",
    "F": "Filipino",
    "G": "Guamanian",
    "H": "Hispanic/Latin/Mexican",
    "I": "American Indian/Alaskan Native",
    "J": "Japanese",
    "K": "Korean",
    "L": "Laotian",
    "O": "Other",
    "P": "Pacific Islander",
    "S": "Samoan",
    "U": "Hawaiian",
    "V": "Vietnamese",
    "W": "White",
    "X": "Unknown",
    "Z": "Asian Indian",
    "-": "Unknown",
    "Unknown": "Unknown"
}

# Apply mapping — creates a new descriptive column
df_clean["Vict Descent Full"] = df_clean["Vict Descent"].map(descent_map).fillna("Unknown")

# keep both (for reference)
df_clean[["Vict Age", "Vict Sex", "Vict Descent", "Vict Descent Full"]].head(15)

    Vict Age Vict Sex Vict Descent       Vict Descent Full
0         31        M            H  Hispanic/Latin/Mexican
1         32        M            H  Hispanic/Latin/Mexican
2         30        M            W                   White
3         47        F            A             Other Asian
4         63        M            H  Hispanic/Latin/Mexican
5         35        M            B                   Black
6         21        F            B                   Black
7         14        F            H  Hispanic/Latin/Mexican
8         43        M            W                   White
9         57        M            W                   White
10        13        M            H  Hispanic/Latin/Mexican
11        34        F            A             Other Asian
12         0  Unknown      Unknown                 Unknown
13         0  Unknown      Unknown                 Unknown
14        32        M            W                   White

In [179]:
# --- Clean Vict Age ---
df_clean["Vict Age"] = df_clean["Vict Age"].apply(
    lambda x: np.nan if x <= 0 or x > 120 else x
)
df_clean["Vict Age"].fillna("Unknown", inplace=True)

print(df_clean["Vict Age"].value_counts().head(10))

Vict Age
Unknown    269359
30.0        22289
35.0        21836
31.0        21420
29.0        21345
28.0        20969
32.0        20844
33.0        20362
27.0        20129
34.0        19419
Name: count, dtype: int64

In [180]:
part_map = {1: "Serious", 2: "Less Serious"}
df_clean["Part_Type"] = df_clean["Part 1-2"].map(part_map)

df_clean[["Part 1-2", "Part_Type"]].head(15)

    Part 1-2     Part_Type
0          2  Less Serious
1          1       Serious
2          2  Less Serious
3          1       Serious
4          1       Serious
5          2  Less Serious
6          2  Less Serious
7          2  Less Serious
8          2  Less Serious
9          2  Less Serious
10         2  Less Serious
11         2  Less Serious
12         1       Serious
13         1       Serious
14         1       Serious

In [181]:
df_clean["Cross Street"] = df_clean["Cross Street"].fillna("Not Applicable")

df_clean[["LOCATION", "Cross Street"]].head(15)

                                    LOCATION Cross Street
0    7800    BEEMAN                       AV      Unknown
1            ATOLL                        AV     N  GAULT
2   14600    SYLVAN                       ST      Unknown
3    6000    COMEY                        AV      Unknown
4                    4700    LA VILLA MARINA      Unknown
5    5300    CRONUS                       ST      Unknown
6     900 W  40TH                         PL      Unknown
7    3000    ACRESITE                     ST      Unknown
8   17700    SIMONDS                      ST      Unknown
9   20900    MARMORA                      ST      Unknown
10   1000 N  RIDGEWOOD                    PL      Unknown
11    400 S  ARDMORE                      AV      Unknown
12  19700    VANOWEN                      ST      Unknown
13   9500    COZYCROFT                    AV      Unknown
14   3300    MOTOR                        AV      Unknown

In [182]:
# Replace both NaN and any lingering "Unknown" values
df_clean["Cross Street"] = (
    df_clean["Cross Street"]
    .replace({"Unknown": "Not Applicable", "": "Not Applicable"})
    .fillna("Not Applicable")
)

# Quick check
df_clean[["LOCATION", "Cross Street"]].head(15)

                                    LOCATION    Cross Street
0    7800    BEEMAN                       AV  Not Applicable
1            ATOLL                        AV        N  GAULT
2   14600    SYLVAN                       ST  Not Applicable
3    6000    COMEY                        AV  Not Applicable
4                    4700    LA VILLA MARINA  Not Applicable
5    5300    CRONUS                       ST  Not Applicable
6     900 W  40TH                         PL  Not Applicable
7    3000    ACRESITE                     ST  Not Applicable
8   17700    SIMONDS                      ST  Not Applicable
9   20900    MARMORA                      ST  Not Applicable
10   1000 N  RIDGEWOOD                    PL  Not Applicable
11    400 S  ARDMORE                      AV  Not Applicable
12  19700    VANOWEN                      ST  Not Applicable
13   9500    COZYCROFT                    AV  Not Applicable
14   3300    MOTOR                        AV  Not Applicable

In [185]:
df_clean.to_csv("CrimeDataCleaned.csv", index=False)
print("Final cleaned dataset saved")

Final cleaned dataset saved

In [186]:
pd.read_csv("CrimeDataCleaned.csv").head(15)

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Has_Multiple_Crimes,All_Crm_Cd,YEAR,MONTH,DAY_OF_WEEK,IS_WEEKEND,TIME_PERIOD,MoCodes_desc,Vict Descent Full,Part_Type
0,211507896,2021-04-11,2020-11-07,08:45,15,N Hollywood,1502,2,354,THEFT OF IDENTITY,...,False,354,2020,11,Saturday,True,Unknown,Takes vict's identification/driver license,Hispanic/Latin/Mexican,Less Serious
1,201516622,2020-10-21,2020-10-18,18:45,15,N Hollywood,1521,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",...,False,230,2020,10,Sunday,True,Unknown,"Hit-Hit w/ weapon, Brandishes weapon, Suspect ...",Hispanic/Latin/Mexican,Serious
2,240913563,2024-12-10,2020-10-30,12:40,9,Van Nuys,933,2,354,THEFT OF IDENTITY,...,False,354,2020,10,Friday,False,Unknown,Takes vict's identification/driver license,White,Less Serious
3,210704711,2020-12-24,2020-12-24,13:10,7,Wilshire,782,1,331,THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...,...,False,331,2020,12,Thursday,False,Unknown,Removes vict property,Other Asian,Serious
4,201418201,2020-10-03,2020-09-29,18:30,14,Pacific,1454,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),...,False,420,2020,9,Tuesday,False,Unknown,"Vehicle involved, Removes vict property, Open/...",Hispanic/Latin/Mexican,Serious
5,240412063,2024-12-11,2020-11-11,12:10,4,Hollenbeck,429,2,354,THEFT OF IDENTITY,...,False,354,2020,11,Wednesday,False,Unknown,Suspect Impersonate,Black,Less Serious
6,240317069,2024-12-16,2020-04-16,13:50,3,Southwest,396,2,354,THEFT OF IDENTITY,...,False,354,2020,4,Thursday,False,Unknown,"Suspect Impersonate, Forged or Fraudulent cred...",Black,Less Serious
7,201115217,2020-10-29,2020-07-07,14:00,11,Northeast,1133,2,812,CRM AGNST CHLD (13 OR UNDER) (14-15 & SUSP 10 ...,...,True,"812, 860",2020,7,Tuesday,False,Unknown,"Victim is 14 years old thru 17 years old, Grab...",Hispanic/Latin/Mexican,Less Serious
8,241708596,2024-04-20,2020-03-02,12:00,17,Devonshire,1729,2,354,THEFT OF IDENTITY,...,False,354,2020,3,Monday,False,Unknown,Other MO (see rpt),White,Less Serious
9,242113813,2024-12-18,2020-09-01,09:00,21,Topanga,2196,2,354,THEFT OF IDENTITY,...,False,354,2020,9,Tuesday,False,Unknown,Unauthorized use of victim's credit/debit card...,White,Less Serious
10,240605846,2024-02-06,2020-06-20,00:01,6,Hollywood,657,2,812,CRM AGNST CHLD (13 OR UNDER) (14-15 & SUSP 10 ...,...,True,"812, 860",2020,6,Saturday,True,Unknown,"Sex related acts, Victim was a student, Victim...",Hispanic/Latin/Mexican,Less Serious
11,242014110,2024-12-18,2020-11-17,13:20,20,Olympic,2023,2,354,THEFT OF IDENTITY,...,False,354,2020,11,Tuesday,False,Unknown,"Suspect Impersonate, Forged or Fraudulent cred...",Other Asian,Less Serious
12,202113531,2020-09-06,2020-09-05,15:00,21,Topanga,2149,1,510,VEHICLE - STOLEN,...,False,510,2020,9,Saturday,True,Unknown,NaN,Unknown,Serious
13,201710725,2020-07-03,2020-07-02,05:00,17,Devonshire,1762,1,310,BURGLARY,...,False,310,2020,7,Thursday,False,Unknown,Removes vict property,Unknown,Serious
14,201406733,2020-02-16,2020-02-13,23:00,14,Pacific,1406,1,330,BURGLARY FROM VEHICLE,...,False,330,2020,2,Thursday,False,Unknown,"Removes vict property, Vehicle involved",White,Serious